{
 "title": "EcoFlow",
 "description": "EcoFlow dashboard",
 "tags": [
  "ecoflow",
  "prometheus",
  "electricity",
  "IoT"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(ecoflow_online, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_online{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ecoflow_bms_status_f32_show_soc{device=\"$device\"}",
     "legendFormat": "Battery Level"
    },
    {
     "expr": "ecoflow_kit_info_watts_soc{device=\"$device\"}",
     "legendFormat": "Slave {{sn}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ecoflow_inv_status_out_temp{device=\"$device\"}",
     "legendFormat": "Inverter"
    },
    {
     "expr": "ecoflow_bms_status_temp{device=\"$device\"}",
     "legendFormat": "BMS"
    },
    {
     "expr": "ecoflow_mppt_status_pv2_mppt_temp{device=\"$device\"}",
     "legendFormat": "PV2"
    },
    {
     "expr": "ecoflow_bms_status_max_cell_temp{device=\"$device\"}",
     "legendFormat": "Max cell"
    },
    {
     "expr": "ecoflow_inv_status_dc_in_temp{device=\"$device\"}",
     "legendFormat": "DC in"
    },
    {
     "expr": "ecoflow_bms_status_min_mos_temp{device=\"$device\"}",
     "legendFormat": "Min MOS"
    },
    {
     "expr": "ecoflow_bms_status_max_mos_temp{device=\"$device\"}",
     "legendFormat": "Max MOS"
    },
    {
     "expr": "ecoflow_bms_status_min_cell_temp{device=\"$device\"}",
     "legendFormat": "Min cell"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(ecoflow_bms_status_f32_show_soc{device=\"$device\"}[10m])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(ecoflow_bms_status_amp{device=\"$device\"}[10m])"
    }
   ]
  },
  {
   "title": "Cycles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_status_cycles{device=\"$device\"}"
    },
    {
     "expr": "ecoflow_bms_slave_status_1_cycles{device=\"$device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ecoflow_bms_slave_status_2_cycles{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_mppt_status_in_watts{device=\"$device\"}",
     "legendFormat": "PV1"
    },
    {
     "expr": "ecoflow_mppt_status_pv2_in_watts{device=\"$device\"}",
     "legendFormat": "PV2"
    },
    {
     "expr": "ecoflow_inv_status_input_watts{device=\"$device\"}",
     "legendFormat": "AC"
    }
   ]
  },
  {
   "title": "Output power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_pd_status_usb1_watts{device=\"$device\"}",
     "legendFormat": "USB 1"
    },
    {
     "expr": "ecoflow_pd_status_usb2_watts{device=\"$device\"}",
     "legendFormat": "USB 2"
    },
    {
     "expr": "ecoflow_pd_status_qc_usb1_watts{device=\"$device\"}",
     "legendFormat": "QC USB 1"
    },
    {
     "expr": "ecoflow_pd_status_qc_usb2_watts{device=\"$device\"}",
     "legendFormat": "QC USB 2"
    },
    {
     "expr": "ecoflow_pd_status_typec1_watts{device=\"$device\"}",
     "legendFormat": "TypeC 1"
    },
    {
     "expr": "ecoflow_pd_status_typec2_watts{device=\"$device\"}",
     "legendFormat": "TypeC 2"
    },
    {
     "expr": "ecoflow_inv_status_output_watts{device=\"$device\"}",
     "legendFormat": "AC"
    },
    {
     "expr": "ecoflow_pd_status_car_watts{device=\"$device\"}",
     "legendFormat": "DC"
    }
   ]
  },
  {
   "title": "AC voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "ecoflow_inv_status_ac_in_vol{device=\"$device\"} > 0",
     "legendFormat": "IN"
    },
    {
     "expr": "ecoflow_inv_status_inv_out_vol{device=\"$device\"} > 0",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Solar voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "ecoflow_mppt_status_in_vol{device=\"$device\"}",
     "legendFormat": "PV1"
    },
    {
     "expr": "ecoflow_mppt_status_pv2_in_vol{device=\"$device\"}",
     "legendFormat": "PV2"
    }
   ]
  },
  {
   "title": "Solar current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "ecoflow_mppt_status_in_amp{device=\"$device\"}",
     "legendFormat": "PV1"
    },
    {
     "expr": "ecoflow_mppt_status_pv2_in_amp{device=\"$device\"}",
     "legendFormat": "PV2"
    }
   ]
  },
  {
   "title": "Grid status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ecoflow_offgrid{device=\"$device\"}",
     "legendFormat": "offgrid"
    }
   ]
  },
  { "title": "Smart plugs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "ecoflow_watts / 10", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "ecoflow_volt", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    { "expr": "ecoflow_current", "legendFormat": "{{device}}" }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "MQTT Messages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "m/s" } },
   "targets": [
    {
     "expr": "rate(ecoflow_mqtt_messages_receive_total{device=\"$device\"}[1m])",
     "legendFormat": "MQTT Messages"
    }
   ]
  }
 ]
}