spring:
  application:
    name: exporter

ecoflow:
  data: /data
  api:
    host: api.ecoflow.com
    email: ${ECOFLOW_USERNAME}
    password: ${ECOFLOW_PASSWORD}
  offlineTimeout: PT1m
  devices: ${ECOFLOW_DEVICES}

httpClient:
  timeout:
    connectTimeout: 1000
    readTimeout: 30000
    socketTimeout: 30000
  connections:
    maxConnections: 2048
    maxConnectionsPerRoute: 2048

management:
  endpoints:
    web:
      exposure:
        include: "info,health,metrics,prometheus"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true