spring:
  application:
    name: exporter

ecoflow:
  api:
    host: api-e.ecoflow.com
    accessKey: ${ECOFLOW_ACCESS_KEY}
    secret: ${ECOFLOW_SECRET}
  offlineTimeout: PT1m
  offgridTimeout: PT1m

httpClient:
  timeout:
    connectTimeout: 1000
    readTimeout: 30000
    socketTimeout: 30000
  connections:
    maxConnections: 2048
    maxConnectionsPerRoute: 2048

management:
  endpoints:
    web:
      exposure:
        include: "info,health,metrics,prometheus"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true